import { Loader2, MessageSquare, Send } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import {
  type CopilotMessage,
  useCopilotChat,
} from "@/controllers/API/queries/copilot/use-copilot-chat";
import { useGenerateWorkflow } from "@/controllers/API/queries/copilot/use-generate-workflow";
import { useCustomNavigate } from "@/customization/hooks/use-custom-navigate";
import useAlertStore from "@/stores/alertStore";
import { cn } from "@/utils/utils";
import { Button } from "../ui/button";
import { Textarea } from "../ui/textarea";

interface CopilotChatProps {
  open: boolean;
  setOpen: (open: boolean) => void;
}

export default function CopilotChat({ open, setOpen }: CopilotChatProps) {
  const [messages, setMessages] = useState<CopilotMessage[]>([]);
  const [inputMessage, setInputMessage] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const navigate = useCustomNavigate();
  const setErrorData = useAlertStore((state) => state.setErrorData);

  const { mutate: chatMutate } = useCopilotChat({
    onSuccess: (data) => {
      setIsGenerating(false);
      if (data.workflow_data) {
        // Add assistant message with workflow info
        const assistantMsg: CopilotMessage = {
          role: "assistant",
          content: data.message,
        };
        setMessages((prev) => [...prev, assistantMsg]);

        // Auto-save workflow
        handleSaveWorkflow(data.workflow_data);
      } else {
        // Regular response
        const assistantMsg: CopilotMessage = {
          role: "assistant",
          content: data.message,
        };
        setMessages((prev) => [...prev, assistantMsg]);
      }
    },
    onError: (error: any) => {
      setIsGenerating(false);
      setErrorData({
        title: "Error",
        list: [error.message || "Failed to generate workflow"],
      });
    },
  });

  const { mutate: generateWorkflow } = useGenerateWorkflow({
    onSuccess: (data) => {
      setErrorData({
        title: "Success",
        list: ["Workflow created successfully!"],
      });
      setOpen(false);
      // Navigate to the new flow
      navigate(`/flow/${data.id}`);
    },
    onError: (error: any) => {
      setErrorData({
        title: "Error",
        list: [error.message || "Failed to save workflow"],
      });
    },
  });

  const handleSaveWorkflow = (workflowData: any) => {
    const flowName = `Copilot Generated Flow ${new Date().toLocaleString()}`;
    generateWorkflow({
      workflow_data: workflowData,
      flow_name: flowName,
      description: "Generated by Copilot Agent",
    });
  };

  const handleSendMessage = () => {
    if (!inputMessage.trim() || isGenerating) return;

    const userMessage: CopilotMessage = {
      role: "user",
      content: inputMessage,
    };

    setMessages((prev) => [...prev, userMessage]);
    setInputMessage("");
    setIsGenerating(true);

    // Prepare conversation history
    const conversationHistory = [...messages, userMessage];

    chatMutate({
      message: inputMessage,
      conversation_history: conversationHistory,
    });
  };

  const handleKeyPress = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  useEffect(() => {
    if (open && messages.length === 0) {
      // Add welcome message
      setMessages([
        {
          role: "assistant",
          content:
            "Hello! I'm your Langflow Copilot. Tell me what kind of workflow you'd like to create, and I'll generate it for you. For example: 'Create a chatbot that answers questions about AI' or 'Build a workflow that summarizes documents'.",
        },
      ]);
    }
  }, [open]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="flex h-[80vh] w-full max-w-4xl flex-col rounded-lg bg-background shadow-lg">
        {/* Header */}
        <div className="flex items-center justify-between border-b p-4">
          <div className="flex items-center gap-2">
            <MessageSquare className="h-5 w-5" />
            <h2 className="text-lg font-semibold">Copilot Agent</h2>
          </div>
          <Button variant="ghost" size="sm" onClick={() => setOpen(false)}>
            Close
          </Button>
        </div>

        {/* Messages */}
        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {messages.map((msg, idx) => (
            <div
              key={idx}
              className={cn(
                "flex",
                msg.role === "user" ? "justify-end" : "justify-start",
              )}
            >
              <div
                className={cn(
                  "max-w-[80%] rounded-lg p-3",
                  msg.role === "user"
                    ? "bg-primary text-primary-foreground"
                    : "bg-muted",
                )}
              >
                <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
              </div>
            </div>
          ))}
          {isGenerating && (
            <div className="flex justify-start">
              <div className="flex items-center gap-2 rounded-lg bg-muted p-3">
                <Loader2 className="h-4 w-4 animate-spin" />
                <p className="text-sm text-muted-foreground">
                  Generating workflow...
                </p>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Input */}
        <div className="border-t p-4">
          <div className="flex gap-2">
            <Textarea
              value={inputMessage}
              onChange={(e) => setInputMessage(e.target.value)}
              onKeyPress={handleKeyPress}
              placeholder="Describe the workflow you want to create..."
              className="min-h-[60px] resize-none"
              disabled={isGenerating}
            />
            <Button
              onClick={handleSendMessage}
              disabled={!inputMessage.trim() || isGenerating}
              size="icon"
              className="h-[60px] w-[60px]"
            >
              {isGenerating ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Send className="h-4 w-4" />
              )}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
